spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application: 
    name: dt-platform-config-dev
  cloud:
    bootstrap:
      enabled: false
    config:
      uri: http://localhost:3344
      name: webclient
      profile: dev
---
spring:
  profiles: test
  application:
    name: dt-platform-config-test
  cloud:
    bootstrap:
      enabled: false
    config:
      uri: http://localhost:3344
      name: webclient
      profile: test
---
spring:
  profiles: prod
  application:
    name: dt-platform-config-prod
  cloud:
    bootstrap:
      enabled: false
    config:
      uri: http://localhost:3344
      name: webclient
      profile: prod
