server: 
  port: 4433
spring:
  profiles: dev #开发环境
  application:
    name: dt-platform-confg-client

eureka:
  client:
    service-url:
      ##defaultZone: http://${eureka.instance.hostname}:7001/eureka/ #将服务注册到Eurka中   ##单机版配置
      ##defaultZone: http://eurka01.com:8761/eureka,http://eurka02.com:8764/eureka,http://eurka03.com:8765/eureka      ## 集群配置举例
      defaultZone: http://152.136.18.82:30867/eureka,http://152.136.18.82:32138/eureka,http://152.136.18.82:30608/eureka,http://152.136.18.82:32138/eureka
#请保存为UTF-8格式
---
server: 
  port: 4434
spring:
  profiles: test #开发环境
  application:
    name: dt-platform-confg-client

eureka:
  client:
    service-url:
      ##defaultZone: http://${eureka.instance.hostname}:7001/eureka/ #将服务注册到Eurka中   ##单机版配置
      ##defaultZone: http://eurka01.com:8761/eureka,http://eurka02.com:8764/eureka,http://eurka03.com:8765/eureka      ## 集群配置举例
      defaultZone: http://152.136.18.82:30867/eureka,http://152.136.18.82:32138/eureka,http://152.136.18.82:30608/eureka,http://152.136.18.82:32138/eureka
