spring: 
  profiles: dev #开发环境
  application: 
    name: dt-platform-user-customer
server: 
    port: 9004
### Feign 配置
feign: 
  # 开启断路器（熔断器）
  hystrix: 
    enabled: true
eureka: 
  client: 
    service-url: 
      #defaultZone: http://eurka01.com:8761/eureka,http://eurka02.com:8764/eureka,http://eurka03.com:8765/eureka     #集群配置
      defaultZone: http://eurka01.com:7001/eureka
    register-with-eureka: false

---
spring: 
  profiles: test #开发环境
  application: 
    name: dt-platform-user-customer
server: 
    port: 9004
### Feign 配置
feign: 
  # 开启断路器（熔断器）
  hystrix: 
    enabled: true
eureka: 
  client: 
    service-url: 
      #defaultZone: http://eurka01.com:8761/eureka,http://eurka02.com:8764/eureka,http://eurka03.com:8765/eureka     #集群配置
      defaultZone: http://eurka01.com:7001/eureka,http://eurka02.com:7002/eureka,http://eurka03.com:7003/eureka
      register-with-eureka: false
